"""enterprise od workflow

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 12:40:04.005732
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None



def _add_fk_column(table: str, column: str, ref_table: str) -> None:
    """Add a nullable integer FK column to an existing table on SQLite and PostgreSQL.

    SQLite cannot ADD CONSTRAINT, but accepts an inline REFERENCES clause on a
    nullable ADD COLUMN, which needs no table rebuild and touches no existing row.
    """
    if op.get_bind().dialect.name == "sqlite":
        op.execute(f"ALTER TABLE {table} ADD COLUMN {column} INTEGER REFERENCES {ref_table} (id)")
    else:
        op.add_column(table, sa.Column(column, sa.Integer(), nullable=True))
        op.create_foreign_key(f"fk_{table}_{column}", table, ref_table, [column], ["id"])


def _drop_fk_columns(table: str, columns: list) -> None:
    if op.get_bind().dialect.name == "sqlite":
        # SQLite refuses to drop a column that carries a foreign key without a
        # full table rebuild. A downgrade leaves these three unused columns in place.
        return
    for column in columns:
        op.drop_constraint(f"fk_{table}_{column}", table, type_="foreignkey")
        op.drop_column(table, column)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('od_hours_per_semester', sa.Float(), nullable=False),
    sa.Column('term_start', sa.Date(), nullable=False),
    sa.Column('term_end', sa.Date(), nullable=False),
    sa.Column('min_attendance_pct', sa.Float(), nullable=False),
    sa.Column('approval_chain', sa.String(), nullable=False),
    sa.Column('hod_threshold_hours', sa.Float(), nullable=False),
    sa.Column('max_hours_per_request', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('department_heads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'user_id', name='uq_department_head')
    )
    op.create_table('stored_files',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('advisor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('ix_advisor_assignments_faculty', 'advisor_assignments', ['faculty_id'], unique=False)
    op.create_table('od_attendance_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('classes_credited', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['od_requests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'subject_id', name='uq_od_credit_request_subject')
    )
    op.create_index('ix_od_credits_student', 'od_attendance_credits', ['student_id'], unique=False)
    op.create_table('od_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['od_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_od_audit_request', 'od_audit_logs', ['request_id'], unique=False)
    op.create_table('od_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(), nullable=True),
    sa.Column('extracted_fields', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['od_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_od_documents_request', 'od_documents', ['request_id'], unique=False)
    op.create_index('ix_od_documents_sha', 'od_documents', ['sha256'], unique=False)
    _add_fk_column('od_requests', 'institution_id', 'institutions')
    _add_fk_column('od_requests', 'advisor_faculty_id', 'faculty')
    _add_fk_column('od_requests', 'hod_user_id', 'users')
    op.add_column('od_requests', sa.Column('workflow_state', sa.String(), nullable=True))
    op.add_column('od_requests', sa.Column('event_name', sa.String(), nullable=True))
    op.add_column('od_requests', sa.Column('organizer', sa.String(), nullable=True))
    op.add_column('od_requests', sa.Column('venue', sa.String(), nullable=True))
    op.add_column('od_requests', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('od_requests', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.add_column('od_requests', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('od_requests', sa.Column('decided_at', sa.DateTime(), nullable=True))
    op.add_column('od_requests', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('od_requests', sa.Column('requires_hod', sa.Boolean(), nullable=True))
    op.add_column('od_requests', sa.Column('clarification_requested', sa.Boolean(), nullable=True))
    op.add_column('od_requests', sa.Column('clarification_text', sa.Text(), nullable=True))
    op.add_column('od_requests', sa.Column('clarification_response', sa.Text(), nullable=True))
    op.add_column('od_requests', sa.Column('decision_comment', sa.Text(), nullable=True))
    op.add_column('od_requests', sa.Column('review_flags', sa.Text(), nullable=True))
    op.add_column('od_requests', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index('ix_od_requests_advisor_state', 'od_requests', ['advisor_faculty_id', 'workflow_state'], unique=False)
    op.create_index('ix_od_requests_state', 'od_requests', ['workflow_state'], unique=False)
    op.create_index('ix_od_requests_student_state', 'od_requests', ['student_id', 'workflow_state'], unique=False)
    # ### end Alembic commands ###

    # Data: populate the new structures from existing rows. Skipped on an empty
    # database (fresh install or a migration target that will receive copied data).
    bind = op.get_bind()
    if bind.execute(sa.text('select count(*) from users')).scalar():
        from app.od_bootstrap import ensure_od_foundation
        print('0002 data bootstrap:', ensure_od_foundation(bind))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_index('ix_od_requests_student_state', table_name='od_requests')
    op.drop_index('ix_od_requests_state', table_name='od_requests')
    op.drop_index('ix_od_requests_advisor_state', table_name='od_requests')
    _drop_fk_columns('od_requests', ['hod_user_id', 'advisor_faculty_id', 'institution_id'])
    op.drop_column('od_requests', 'version')
    op.drop_column('od_requests', 'review_flags')
    op.drop_column('od_requests', 'decision_comment')
    op.drop_column('od_requests', 'clarification_response')
    op.drop_column('od_requests', 'clarification_text')
    op.drop_column('od_requests', 'clarification_requested')
    op.drop_column('od_requests', 'requires_hod')
    op.drop_column('od_requests', 'cancelled_at')
    op.drop_column('od_requests', 'decided_at')
    op.drop_column('od_requests', 'submitted_at')
    op.drop_column('od_requests', 'end_at')
    op.drop_column('od_requests', 'start_at')
    op.drop_column('od_requests', 'venue')
    op.drop_column('od_requests', 'organizer')
    op.drop_column('od_requests', 'event_name')
    op.drop_column('od_requests', 'workflow_state')
    op.drop_index('ix_od_documents_sha', table_name='od_documents')
    op.drop_index('ix_od_documents_request', table_name='od_documents')
    op.drop_table('od_documents')
    op.drop_index('ix_od_audit_request', table_name='od_audit_logs')
    op.drop_table('od_audit_logs')
    op.drop_index('ix_od_credits_student', table_name='od_attendance_credits')
    op.drop_table('od_attendance_credits')
    op.drop_index('ix_advisor_assignments_faculty', table_name='advisor_assignments')
    op.drop_table('advisor_assignments')
    op.drop_table('stored_files')
    op.drop_table('department_heads')
    op.drop_table('institutions')
    # ### end Alembic commands ###
